# Generated by Django 5.0.3 on 2024-03-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
    ]
