# Generated by Django 5.0.3 on 2024-03-28 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_remove_doctor_doctor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_id',
            field=models.CharField(default=10000, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
