# Generated by Django 5.0.3 on 2024-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_doctor_contact_information_doctor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
