# Generated by Django 5.0.3 on 2024-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0017_alter_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
