# Generated by Django 5.0.3 on 2024-03-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0018_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'patient')},
        ),
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('personal_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('drug_history', models.TextField(blank=True)),
                ('vital_signs', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('xray_image', models.ImageField(blank=True, upload_to='ehr/xray/')),
                ('lab_result_image', models.ImageField(blank=True, upload_to='ehr/lab_result/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
            options={
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
