# Generated by Django 5.0.3 on 2024-03-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0019_alter_appointment_unique_together_ehr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehr',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
